package am.ik.redis.adapter.boot;

import java.io.File;
import java.io.IOException;
import java.time.Duration;
import java.util.function.Function;

import am.ik.redis.adapter.server.RedisAdapterServer;
import io.lettuce.core.ClientOptions;
import io.lettuce.core.RedisClient;
import io.lettuce.core.RedisException;
import io.lettuce.core.RedisURI;
import io.lettuce.core.SslOptions;
import io.lettuce.core.api.StatefulRedisConnection;
import io.lettuce.core.codec.StringCodec;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.Test;

import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.autoconfigure.ssl.SslAutoConfiguration;
import org.springframework.boot.ssl.NoSuchSslBundleException;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.core.io.ClassPathResource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Covers what {@code redis-adapter.ssl.*} does to the running server, over a real Lettuce
 * client speaking real TLS to a real socket. Whether a port is encrypted is only ever
 * answered on the wire: a server that had built an {@code SSLContext} and then bound a
 * plain socket would satisfy any assertion made on the beans.
 *
 * <p>
 * The certificates come from {@code src/test/resources/tls}, generated by the
 * {@code generate-test-certificates.sh} next to them. A throwaway CA signs both the
 * server's certificate and the client's, so each side is verified the way a deployment
 * verifies it, host name included — the server certificate carries {@code 127.0.0.1} as a
 * subject alternative name, which is the address these tests dial.
 */
class RedisAdapterServerTlsConfigurationTests {

	/**
	 * The bundle every case has available, whether or not it names it. Its trust store is
	 * the test CA, which is what the client certificates of the mutual-TLS cases are
	 * verified against.
	 */
	private final ApplicationContextRunner runner = new ApplicationContextRunner()
		.withConfiguration(AutoConfigurations.of(SslAutoConfiguration.class))
		.withUserConfiguration(KeyValueStoreConfiguration.class, RedisAdapterServerConfiguration.class)
		.withPropertyValues("redis-adapter.bind-address=127.0.0.1", "redis-adapter.port=0",
				"spring.ssl.bundle.pem.adapter.keystore.certificate=classpath:tls/server.crt",
				"spring.ssl.bundle.pem.adapter.keystore.private-key=classpath:tls/server.key",
				"spring.ssl.bundle.pem.adapter.truststore.certificate=classpath:tls/ca.crt");

	/**
	 * Naming a bundle is the whole of switching TLS on, and it is switched on for
	 * everyone: the plain client that worked a moment ago no longer gets an answer.
	 */
	@Test
	void servesTlsWhenGivenABundle() {
		this.runner.withPropertyValues("redis-adapter.ssl.bundle=adapter").run(context -> {
			int port = context.getBean(RedisAdapterServer.class).port();

			assertThat(pingOverTls(port, null)).isEqualTo("PONG");
			assertThatThrownBy(() -> pingOverPlainTcp(port)).isInstanceOf(RedisException.class);
		});
	}

	/**
	 * The default is plain TCP, which is what an application that never asked for TLS
	 * keeps getting.
	 */
	@Test
	void staysPlainWhenNoBundleIsNamed() {
		this.runner.run(context -> {
			int port = context.getBean(RedisAdapterServer.class).port();

			assertThat(pingOverPlainTcp(port)).isEqualTo("PONG");
		});
	}

	/**
	 * Falling back to plain TCP is allowed, but only in writing. An operator who leaves
	 * the bundle configured and sets {@code enabled=false} has said what they meant; one
	 * who merely forgets a property is served TLS all the same.
	 */
	@Test
	void servesPlainTcpWhenTlsIsExplicitlyDisabled() {
		this.runner.withPropertyValues("redis-adapter.ssl.bundle=adapter", "redis-adapter.ssl.enabled=false")
			.run(context -> {
				int port = context.getBean(RedisAdapterServer.class).port();

				assertThat(pingOverPlainTcp(port)).isEqualTo("PONG");
			});
	}

	/**
	 * Asking for TLS without saying what to serve it with is the mistake that would
	 * otherwise end in a plain port nobody looks at again, so it stops the application.
	 */
	@Test
	void refusesToStartWhenTlsIsEnabledWithoutABundle() {
		this.runner.withPropertyValues("redis-adapter.ssl.enabled=true")
			.run(context -> assertThat(context).hasFailed()
				.getFailure()
				.rootCause()
				.hasMessage("redis-adapter.ssl.enabled is true but redis-adapter.ssl.bundle names no SSL bundle"));
	}

	@Test
	void refusesToStartWhenTheBundleIsUnknown() {
		this.runner.withPropertyValues("redis-adapter.ssl.bundle=nowhere")
			.run(context -> assertThat(context).hasFailed()
				.getFailure()
				.rootCause()
				.isInstanceOf(NoSuchSslBundleException.class));
	}

	/**
	 * Mutual TLS: under {@code need} the certificate is the credential, so a client
	 * without one is refused before it can run a command.
	 */
	@Test
	void requiresAClientCertificateWhenClientAuthIsNeed() {
		this.runner.withPropertyValues("redis-adapter.ssl.bundle=adapter", "redis-adapter.ssl.client-auth=need")
			.run(context -> {
				int port = context.getBean(RedisAdapterServer.class).port();

				assertThat(pingOverTls(port, clientCertificate())).isEqualTo("PONG");
				assertThatThrownBy(() -> pingOverTls(port, null)).isInstanceOf(RedisException.class);
			});
	}

	/**
	 * Under {@code want} the certificate is asked for and its absence is not held against
	 * the client, which is what makes it usable while clients are still being issued
	 * certificates.
	 */
	@Test
	void servesAClientWithoutACertificateWhenClientAuthIsWant() {
		this.runner.withPropertyValues("redis-adapter.ssl.bundle=adapter", "redis-adapter.ssl.client-auth=want")
			.run(context -> {
				int port = context.getBean(RedisAdapterServer.class).port();

				assertThat(pingOverTls(port, null)).isEqualTo("PONG");
				assertThat(pingOverTls(port, clientCertificate())).isEqualTo("PONG");
			});
	}

	/**
	 * The client-side trust material: the test CA, which is what makes the adapter's
	 * certificate acceptable to a client that verifies it.
	 * @return SSL options trusting the test CA and presenting nothing
	 * @throws IOException if the certificate cannot be read
	 */
	private static SslOptions trustingTheTestCa() throws IOException {
		return SslOptions.builder().trustManager(resource("tls/ca.crt")).build();
	}

	/**
	 * The client-side material of a client that also identifies itself.
	 * @return SSL options trusting the test CA and presenting the test client certificate
	 * @throws IOException if the certificate or key cannot be read
	 */
	private static SslOptions clientCertificate() throws IOException {
		return SslOptions.builder()
			.trustManager(resource("tls/ca.crt"))
			.keyManager(resource("tls/client.crt"), resource("tls/client.key"), null)
			.build();
	}

	private static File resource(String name) throws IOException {
		return new ClassPathResource(name).getFile();
	}

	/**
	 * Runs {@code PING} over TLS.
	 * @param port where the adapter listens
	 * @param sslOptions what the client presents and trusts, or {@code null} to trust the
	 * test CA and present nothing
	 * @return the reply
	 * @throws IOException if the certificates cannot be read
	 */
	private static String pingOverTls(int port, @Nullable SslOptions sslOptions) throws IOException {
		return connected(uri(port).withSsl(true).build(), (sslOptions != null) ? sslOptions : trustingTheTestCa(),
				connection -> connection.sync().ping());
	}

	private static String pingOverPlainTcp(int port) {
		return connected(uri(port).build(), null, connection -> connection.sync().ping());
	}

	private static RedisURI.Builder uri(int port) {
		return RedisURI.builder().withHost("127.0.0.1").withPort(port).withTimeout(Duration.ofSeconds(10));
	}

	/**
	 * Runs an action on a live connection to the adapter, over the same client an
	 * application would use.
	 * @param uri where and how to connect
	 * @param sslOptions the client's TLS material, or {@code null} for a plain connection
	 * @param action what to do with the connection
	 * @return whatever the action returned
	 */
	private static <T> T connected(RedisURI uri, @Nullable SslOptions sslOptions,
			Function<StatefulRedisConnection<String, String>, T> action) {
		RedisClient client = RedisClient.create();
		if (sslOptions != null) {
			client.setOptions(ClientOptions.builder().sslOptions(sslOptions).build());
		}
		try (StatefulRedisConnection<String, String> connection = client.connect(StringCodec.UTF8, uri)) {
			return action.apply(connection);
		}
		finally {
			client.shutdown(Duration.ZERO, Duration.ofSeconds(10));
		}
	}

}
